server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task_2
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

